import {
  Button,
  Code,
  Container,
  HStack,
  Text,
  VStack,
} from '@chakra-ui/react';
import { useState } from 'react';

export default function UseState() {
  const [count, setCount] = useState(0);

  return (
    <Container
      minH="100vh"
      minW="100vw"
      bg="gray.900"
      display="flex"
      flexDir="column"
      justifyContent="center"
      alignItems="center"
      gap={10}
      color="whiteAlpha.900"
    >
      <Container
        maxW="4xl"
        textAlign="center"
      >
        <VStack
          my={4}
          p={4}
          border="2px solid"
          borderColor="gray.600"
          rounded={8}
          bg="gray.700"
          alignItems="flex-start"
        >
          <Text fontSize={20}>What&apos;s Happening?</Text>
          <Text textAlign="left">
            We&apos;re using the <Code children="useState" /> hook to manage the
            state of a number. We have a variable &amp; function assigned to
            this state management, in this case they&apos;re labeled{' '}
            <Code children="count" /> &amp; <Code children="setCount" />{' '}
            respectively. Our two buttons below call the{' '}
            <Code children="setCount" /> function in the{' '}
            <Code children="onClick" /> event to increment and decrement the
            value assigned our <Code children="count" /> variable.
          </Text>
          <Text>
            Under our implementation you&apos;ll see an example of how to
            implement this code yourself.
          </Text>
        </VStack>
        <Text fontSize={50}>Use State Return: {count}</Text>
        <HStack
          alignItems="center"
          justifyContent="center"
          gap={6}
        >
          <Button onClick={() => setCount((prev) => prev + 1)}>
            Increment Count
          </Button>
          <Button onClick={() => setCount((prev) => prev - 1)}>
            Decrement Count
          </Button>
        </HStack>
        <VStack
          mt={8}
          p={4}
          border="2px solid"
          borderColor="gray.600"
          rounded={8}
          bg="gray.700"
          alignItems="flex-start"
        >
          <Code
            bg="unset"
            children={
              <Text color="purple.400">
                import&nbsp;
                <Text
                  as="span"
                  color="yellow.400"
                >
                  &#123;
                </Text>
                <Text
                  as="span"
                  color="blue.400"
                >
                  &nbsp;useState&nbsp;
                </Text>
                <Text
                  as="span"
                  color="yellow.400"
                >
                  &#125;&nbsp;
                </Text>
                from&nbsp;
                <Text
                  as="span"
                  color="orange.400"
                >
                  &apos;react&apos;
                </Text>
                <Text
                  as="span"
                  color="whiteAlpha.900"
                >
                  &#59;
                </Text>
              </Text>
            }
          />
          <Code
            bg="unset"
            children="&nbsp;"
          />
          <Code
            bg="unset"
            children={
              <Text color="purple.400">
                export default&nbsp;
                <Text
                  as="span"
                  color="blue.400"
                >
                  function
                </Text>
                &nbsp;
                <Text
                  as="span"
                  color="yellow.100"
                >
                  MyFunction
                </Text>
                <Text
                  as="span"
                  color="yellow.400"
                >
                  &#40;&#41;&nbsp;&#123;
                </Text>
              </Text>
            }
          />
          <Code
            bg="unset"
            children={
              <Text color="blue.400">
                &nbsp;&nbsp;const&nbsp;
                <Text
                  as="span"
                  color="purple.400"
                >
                  &#91;
                </Text>
                <Text
                  as="span"
                  color="blue.400"
                >
                  count
                </Text>
                <Text
                  as="span"
                  color="whiteAlpha.900"
                >
                  &#44;&nbsp;
                </Text>
                <Text
                  as="span"
                  color="yellow.100"
                >
                  setCount
                </Text>
                <Text
                  as="span"
                  color="purple.400"
                >
                  &#93;&nbsp;
                </Text>
                <Text
                  as="span"
                  color="whiteAlpha.900"
                >
                  &#61;&nbsp;
                </Text>
                <Text
                  as="span"
                  color="yellow.100"
                >
                  useState
                </Text>
                <Text
                  as="span"
                  color="purple.400"
                >
                  &#40;
                </Text>
                <Text
                  as="span"
                  color="green.100"
                >
                  0
                </Text>
                <Text
                  as="span"
                  color="purple.400"
                >
                  &#41;
                </Text>
                <Text
                  as="span"
                  color="whiteAlpha.900"
                >
                  &#59;
                </Text>
              </Text>
            }
          />
          <Code
            bg="unset"
            children={<Text color="purple.400">&nbsp;&nbsp;return &#40;</Text>}
          />
          <Code
            bg="unset"
            children={
              <>
                <Text color="gray.400">
                  &nbsp;&nbsp;&nbsp;&nbsp;&#60;
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    div
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#62;
                  </Text>
                </Text>
              </>
            }
          />
          <Code
            bg="unset"
            children={
              <>
                <Text color="gray.400">
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#60;
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    p
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#62;
                  </Text>
                  <Text
                    as="span"
                    color="whiteAlpha.900"
                  >
                    Use State Return&#58;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    &#123;
                  </Text>
                  <Text
                    as="span"
                    color="blue.200"
                  >
                    count
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    &#125;
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#60;
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#47;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    p
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#62;
                  </Text>
                </Text>
              </>
            }
          />
          <Code
            bg="unset"
            children={
              <>
                <Text color="gray.400">
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#60;
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    button&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="blue.200"
                  >
                    onClick
                  </Text>
                  <Text
                    as="span"
                    color="whiteAlpha.900"
                  >
                    &#61;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    &#123;
                  </Text>
                  <Text
                    as="span"
                    color="yellow.400"
                  >
                    &#40;&#41;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    &#61;&#62;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="yellow.100"
                  >
                    setCount
                  </Text>
                  <Text
                    as="span"
                    color="yellow.400"
                  >
                    &#40;
                  </Text>
                  <Text
                    as="span"
                    color="purple.400"
                  >
                    &#40;
                  </Text>
                  <Text
                    as="span"
                    color="blue.200"
                  >
                    prev
                  </Text>
                  <Text
                    as="span"
                    color="purple.400"
                  >
                    &#41;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    &#61;&#62;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    prev&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="whiteAlpha.900"
                  >
                    &#43;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="green.100"
                  >
                    1
                  </Text>
                  <Text
                    as="span"
                    color="yellow.400"
                  >
                    &#41;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    &#125;
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#62;
                  </Text>
                  <Text
                    as="span"
                    color="whiteAlpha.900"
                  >
                    Increment Count
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#60;
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#47;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    button
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#62;
                  </Text>
                </Text>
              </>
            }
          />
          <Code
            bg="unset"
            children={
              <>
                <Text color="gray.400">
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#60;
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    button&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="blue.200"
                  >
                    onClick
                  </Text>
                  <Text
                    as="span"
                    color="whiteAlpha.900"
                  >
                    &#61;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    &#123;
                  </Text>
                  <Text
                    as="span"
                    color="yellow.400"
                  >
                    &#40;&#41;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    &#61;&#62;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="yellow.100"
                  >
                    setCount
                  </Text>
                  <Text
                    as="span"
                    color="yellow.400"
                  >
                    &#40;
                  </Text>
                  <Text
                    as="span"
                    color="purple.400"
                  >
                    &#40;
                  </Text>
                  <Text
                    as="span"
                    color="blue.200"
                  >
                    prev
                  </Text>
                  <Text
                    as="span"
                    color="purple.400"
                  >
                    &#41;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    &#61;&#62;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    prev&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="whiteAlpha.900"
                  >
                    &#45;&nbsp;
                  </Text>
                  <Text
                    as="span"
                    color="green.100"
                  >
                    1
                  </Text>
                  <Text
                    as="span"
                    color="yellow.400"
                  >
                    &#41;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    &#125;
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#62;
                  </Text>
                  <Text
                    as="span"
                    color="whiteAlpha.900"
                  >
                    Decrement Count
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#60;
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#47;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    button
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#62;
                  </Text>
                </Text>
              </>
            }
          />
          <Code
            bg="unset"
            children={
              <>
                <Text color="gray.400">
                  &nbsp;&nbsp;&nbsp;&nbsp;&#60;
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#47;
                  </Text>
                  <Text
                    as="span"
                    color="blue.400"
                  >
                    div
                  </Text>
                  <Text
                    as="span"
                    color="gray.400"
                  >
                    &#62;
                  </Text>
                </Text>
              </>
            }
          />
          <Code
            bg="unset"
            children={
              <Text color="purple.400">
                &nbsp;&nbsp;&#41;
                <Text
                  as="span"
                  color="whiteAlpha.900"
                >
                  &#59;
                </Text>
              </Text>
            }
          />
          <Code
            bg="unset"
            children={
              <>
                <Text color="yellow.400">&#125;</Text>
              </>
            }
          />
        </VStack>
      </Container>
    </Container>
  );
}
